/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124419-gc8a4770599-20260508"
#endif /* AVUTIL_FFVERSION_H */
